CREATE DATABASE [TopDown]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TopDown', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\TopDown.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TopDown_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\TopDown_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TopDown] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [TopDown] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TopDown] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TopDown] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TopDown] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TopDown] SET ARITHABORT OFF 
GO
ALTER DATABASE [TopDown] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TopDown] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TopDown] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [TopDown] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TopDown] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TopDown] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TopDown] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TopDown] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TopDown] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TopDown] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TopDown] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TopDown] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TopDown] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TopDown] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TopDown] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TopDown] SET  READ_WRITE 
GO
ALTER DATABASE [TopDown] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TopDown] SET  MULTI_USER 
GO
ALTER DATABASE [TopDown] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TopDown] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TopDown] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TopDown]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [TopDown]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TopDown] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

CREATE TABLE Orders (
    OrderID INT IDENTITY PRIMARY KEY,
    CustomerName VARCHAR(50),
    OrderDate DATE
)
GO

CREATE TABLE OrderItems (
    OrderItemID INT IDENTITY PRIMARY KEY,
    OrderID INT,
    ProductName VARCHAR(60),
    Quantity INT,
    Price DECIMAL(10, 2),
    CONSTRAINT UC_OrderProduct UNIQUE (OrderID, ProductName)
)
GO